### ISSUE TITLE
Random crash (Linux, xdotool)

### ISSUE THREAD

**Issue by Zedtho** [Zedtho/Smack#19]
While opening QML creator studio with Smack, I noticed the following log, which then resulted in an error. Fix this issue.

INFO:root:Screen01.ui.qml (SmackContent @ Smack) [main] - Qt Design Studio
INFO:root:Querying wildcardlist
INFO:root:Querying wildcardlist
INFO:root:Querying wildcardlist
Traceback (most recent call last):
  File "/home/[redacted]/Repos/Smack/smack.py", line 169, in <module>
    content = input_output.read_title()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[redacted]/Repos/Smack/input_output/linux_io.py", line 12, in read_title
    return subprocess.check_output(['xprop', '-id', active_window_id, 'WM_NAME'], stderr=subprocess.DEVNULL).strip().decode('utf-8').split(' = ', 1)[1].strip('"')
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Zedtho** [comment]
Possibly fixed in 7d62751dc2c393162b78d3677a102f2bac17f558 (simply ignore the warning). Will have to check if it works.
